# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 497fd6110d64115fc09ded13586ac75e33148198e33d0aba9cecdf8bb2547ca3df9b812a29a903ded07e38658b9fe526aa0ae808f3845bbeca5f5097ca3c0ae9

test:
  secret_key_base: ac87dd9a9c21e011f71680e4d3dc3aedf2018ab800ba8b5dc54ba961448e48e1a54c946014e59947974e6974f64c452564f9f19cece7d0806b6e2657b6b06c45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
